version: '1.0'
services:
  nodejs:
    build:
      context: .
    image: node/mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=test
      - MYSQL_USER=ananth
      - MYSQL_PASS=Ananth@123
    volumes:
      - ./www/:/var/www/html/
    ports:
      - 8000:8000
    container_name: node-app
  mysql:
    image: mysql:latest
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ananth
      - MYSQL_PASSWORD=Ananth@123
    container_name: sql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      - PMA_HOST=sql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: